services:
  db:
    image: mysql:8.4
    container_name: aztggdb-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aztggdb
    ports:
      - "3306:3306"
    volumes:
      - ./init-mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped
  redis:
    image: "bitnami/redis:7.2.4"
    hostname: aztgg-redis
    container_name: aztgg-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
